export const NewData = {
  projects: [
    {
      title: "1. AWS CLOUD COMPUTING",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/101.gif",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "AWS CLI","Snapshot",
"AWS Global Network",
"Storage",
"EBS",
"EFS(Elastic file system)",
"API Gateway",
"Cloud Watch",
"Route 53",
"Virtual Private Cloud",
"AWS Serverless",
"AWS Load Balancer Service",
"Monitoring & Scaling",
"Access Management",
"AMI",
"Networking",
"Security & Automation",
"Amazon Rekognition",
"Introduction to AWS AI Services",
"Amazon Comprehend",
"Amazon Transcribe",
"Amazon Translate",
"Amazon Forecast"
      ],
      registerLink: "https://rzp.io/rzp/tN0AHIT",
      originalPrice: "8,000",
      price: "5,500",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "2.PYTHON PROGRAMMING",
      description: "Develop High-End Next Generation End to End DevOps Pipeline Managed Service in High Performance Cloud Computing Platform.",
      image: {
        src: "/assets/Projects/101.gif",
        alt: "DevOps Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
       " Anaconda and Jupyter Notebook",
"Variables and Data Types",
"Running Python Programs",
"Python Data Structures",
"Arithmetic Operations and Operators",
"Regular Expressions",
"Control Structures: Conditional Statements and Loops",
"Functions and Arguments",
"Working with Files and Directories",
"Python Modules and Packages",
"Exception Handling",
"Multi-Threading And Socket Programming",
"Python Object-Oriented Programming ",],
      registerLink: "https://rzp.io/rzp/OHIOmeR ",
      originalPrice: "8,000",
      price: "5,500",
      projectCode: "LW-PSI-SP-101"
    },
    {
      title: "3. PYTHON FULL STACK WEB DEVELOPMENT",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/101.gif",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Web Development Concepts",
        "Static Web Page",
        "Dynamic Web Page",
        "API",
        "GET & POST Method",
        "POSTMAN",
        "HTTPD Web Server",
        "HTML Form",
        "DOM",
        "DOM TREE",
        "TABLES",
        "JavaScript",
        "EVENTS",
        "Asynchronous Java Script",
        "Data Types in Java Script",
        "REGEX",
        "Loops",
        "Arrays",
        "React.js",
        "Bootstrap",
        "Python",
        "Git And GitHub",
        "Flask",
        "MySQL",
       
      ],
      registerLink: "https://rzp.io/rzp/7bVgfUe",
      originalPrice: "8,000",
      price: "5,500 ",
      projectCode: "LW-PSI-SP-100"
    },

    {
      title: "4. MACHINE LEARNING - AI",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/101.gif",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Python",
"Data Science",
"Keras",
"Pandas",
"Deep learning",
"Reinforcement Learning",
"Numpy",
"Classification",
"Clustering",
"Supervised Learning",
"Un Supervised Learning",
"Feature Engineering",
"CNN",
"Traditional Machine Learning Techniques",
"Computer Vision",
"NLP",
"Preprocessing Data",
"Model Evaluation",
"Neural Network",
"Validation Techniques",
"Hyperparameter Tuning",
"Optimization",
      ],
      registerLink: "https://rzp.io/rzp/NV4dSzP",
      originalPrice: "8,000",
      price: "5,500 ",
      projectCode: "LW-PSI-SP-100"
    },
   
    {
      title: "5. MERN STACK DEVELOPMENT",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/101.gif",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Web Development Concepts",
        "HTML",
        "CSS",
        "JavaScript",
        "MACHINE LEARNING-AI",
        "React JS",
        "Node JS",
        "Express JS",
        "MongoDB",
        "Hooks",
        "Document Object Model (DOM)",
        "Routing and APIs",
        "Asynchronous Programming",
        "Building RESTful APIs",
        "Fetching Data from API",
        "Handling Forms and User Input",
        "MERN STACK DEVELOPMENT",
        "Code Organization and Structure",
        "Error Handling"
      ],
      registerLink: "https://rzp.io/rzp/iADTiZcf ",
      originalPrice: "10,000",
      price: "6,500",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "6. GENERATIVE AI + MACHINE LEARNING",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/101.gif",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Python",
        "Data Science",
        "Keras",
        "Pandas",
        "Deep Learning",
        "Reinforcement Learning",
        "Numpy",
        "Classification",
        "Clustering",
        "Supervised Learning",
        "Unsupervised Learning",
        "Feature Engineering",
        "CNN",
        "Traditional Machine Learning Techniques",
        "Computer Vision",
        "NLP",
        "Preprocessing Data",
        "Model Evaluation",
        "Neural Network",
        "Validation Techniques",
        "Hyperparameter Tuning",
        "Optimization",
        "Generative AI and its Applications",
        "Generative Models",
        "Discriminative Models",
        "Generative Adversarial Networks (GANs)",
        "Variational Autoencoders (VAEs)",
        "Pre-trained ML Models",
        "Data Preprocessing in Generative AI Workflows",
        "Feature Extractors",
        "Transfer Learning Techniques",
        "Integrating ML with Generative AI",
        "TensorFlow",
        "PyTorch",
        "Conditional Generation",
        "Controlling Generative Models",
        "Image Synthesis Techniques"
    ],
    
      registerLink: "https://rzp.io/rzp/P38nPnDN ",
      originalPrice: "13,000",
      price: "8,500",
      projectCode: "LW-PSI-SP-100"
    },
   
    {
      title: "7. FULL STACK + MACHINE LEARNING",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/101.gif",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Data Science with Python",
        "Applied Statistics",
        "Supervised Learning - Multiple Variable Linear Regression",
        "Unsupervised Learning - K-means Clustering",
        "Ensemble Techniques - Decision Trees",
        "Featurization, Model Selection & Tuning - Feature Engineering",
        "Recommendation Systems - Introduction to Recommendation Systems",
        "Web Development Concepts",
        "HTML",
        "CSS",
        "JavaScript",
        "React.js",
        "Bootstrap",
        "Python",
        "Git and GitHub",
        "Flask",
        "MySQL"
    ],
    
      registerLink: "https://rzp.io/rzp/lNBx1DEx ",
      originalPrice: "14,000",
      price: "8,500 ",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "8. CLOUD COMPUTING + FULL STACK WEB DEVELOPMENT",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/101.gif",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Web Development Concepts",
        "HTML",
        "CSS",
        "JavaScript",
        "React.js",
        "Bootstrap",
        "Python",
        "Git and GitHub",
        "Flask",
        "MySQL",
        "AWS CLI",
        "Snapshot",
        "AWS Global Network",
        "Storage",
        "EBS",
        "EFS (Elastic File System)",
        "API Gateway",
        "CloudWatch",
        "Route 53",
        "Virtual Private Cloud",
        "AWS Serverless",
        "AWS Load Balancer Service",
        "Monitoring & Scaling",
        "Access Management",
        "AMI",
        "NFS",
        "Networking",
        "Security & Automation",
        "Amazon Rekognition",
        "Introduction to AWS AI Services",
        "Amazon Transcribe",
        "Amazon Translate",
        "Amazon Comprehend",
        "Amazon Forecast"
    ],
      registerLink: "https://rzp.io/rzp/PECaeig",
      originalPrice: "14,000",
      price: "8,500 ",
      projectCode: "LW-PSI-SP-100"
    },
   
  ]
};

  

